import '../styles/globals.css'
import { ThemeProvider } from "@material-ui/styles";
import theme from "../components/theme";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
  <ThemeProvider theme={theme}>
  <Head>
    <title>UILab Task</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <link rel="preconnect" href="https://fonts.googleapis.com" crossorigin />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700&display=swap"
      rel="stylesheet"
    />
  </Head>

  <Component {...pageProps} />
</ThemeProvider>
  );
}

export default MyApp
